### ISSUE TITLE
False positive validation failures

### ISSUE THREAD

**Issue by danielhers** [huji-nlp/ucca#113]
See, for example, https://travis-ci.org/github/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/jobs/749979825

Many new failures are detected by the validation, but looking at the data, they are not correct.

**Comment by lovodkin93** [comment]
Where is the data that was validated?
Also, some of the errors there are actually correct (everything related to Q, "E unit with N siblings", "S unit with C siblings", "E unit with P siblings", "A unit with C, E siblings" from what I saw now).

**Comment by danielhers** [comment]
The data is the XML files in https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT, but the other repositories (e.g. UCCA_German-20K) fail too.
Could you please try to pinpoint which failures are correct and report (some of) them to Dotan? And the incorrect ones should be fixed.

**Comment by lovodkin93** [comment]
I have checked and all the issues were correctly diagnosed and need to be corrected. There was not any problem with the code.
