### ISSUE TITLE
from_json in convert.py doesn't seem to compatible with updated UCCAApp format

### ISSUE THREAD

**Issue by jakpra** [huji-nlp/ucca#34]
convert.from_json still uses deprecated fields of annotation_units like 'annotation_unit_tree_id' and 'parent_id', which have been renamed 'tree_id' and 'parent_tree_id', respectively.

After fixing this locally, I still get errors related to the 'name' field in categories, which might have been removed or moved somewhere else, too.

**Comment by jakpra** [comment]
Fixed the category['name'] issue too by reading the category list of the layer. But now the handling of remote units seems off. @danielhers could you have a look?

If you want I can make a pull request for the things I've already fixed locally (see above).

**Comment by danielhers** [comment]
Thanks @jakpra. The UCCAApp API has been actively changing and I haven't kept pace with it (we haven't been using it for a while).
Yes, please create a PR and I can take a look at the remote units once everything else at least works.
