### ISSUE TITLE
Support for coordinated main relations

### ISSUE THREAD

**Issue by danielhers** [huji-nlp/ucca#57]
UCCA-App now contains a category `Coordinated_Main_Rel.`. As of https://github.com/danielhers/ucca/commit/5406b6981c437d246e4a84faadb082312a83f46a, it is ignored when converting from JSON to XML, but the proper solution is to convert it as follows:

1. Split the Centers inside the main relation to be the main relations of separate Parallel Scenes
2. Move the Connector inside the main relation to be a Linker between the new Parallel Scenes
3. Attach any element of the scene as remotes of the second Parallel Scene

@omriabnd

**Comment by danielhers** [comment]
Guidelines:

If two or more coordinated Processes or two or more coordinated States share exactly the same scene elements (As, Ds, Ts), then we unite them under one parent unit which is assigned two categories: Coordinated Main Relation (CMR) and also P or S accordingly. Internally, we use multiple Cs to mark each Main Relation separately. 
so: John [wrote_C and_N recorded_C]_P+CMR a song on Tuesday

On the other hand, if the coordinated Main Relations don't share one of the Scene elements, we separate them into different scenes.
[John_A [woke up]_P]_A,]_H [went_P [to school]_A (John)_A]_H and [met_P Mary_A there_A (John)]_H

**Comment by danielhers** [comment]
Example: https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/blob/master-images/001961-0002.svg
[[Rusted out]_C and_N unsafe_C]_S cars_A*
should be
[[[Rusted out]_S cars_A*]_H and_L [unsafe_S cars_A*]_H]_S

**Comment by nschneid** [comment]
@danielhers Could you please update the images to reflect the CMR normalization?

**Comment by danielhers** [comment]
@nschneid Done. It happens automatically but it just took a while for the [Travis CI job](https://travis-ci.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/jobs/186991254) to finish.

**Comment by nschneid** [comment]
Great. I did some spot checks and they mostly look good—at least, the ones where the graph wasn't too tangled to read. :) Found one thing that I'm opening as a new issue.
