### ISSUE TITLE
CMR normalization issue for relational nouns

### ISSUE THREAD

**Issue by nschneid** [huji-nlp/ucca#62]
Re: #57 

https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/blob/f30dc0dbc9196423336dac8ea0b4f1e3e89958f3/194313-0004.svg

before normalization: https://github.com/UniversalConceptualCognitiveAnnotation/UCCA_English-EWT/blob/2083a4f00d14244390f9df4964410a6d419946c9/194313-0004.svg

I think the CMR-normalized analysis should be:
[[My_A wife_S+A]_C and_N [(My)_A kids_S+A]_C]_A

**Comment by danielhers** [comment]
Thanks! I did some eyeballing of results but it's always good to have more checks.
So you're saying that in case the main relation is also a participant, the normalized version should not be changed to Parallel Scenes + Linker, but rather stay Centers + Connector, right?

**Comment by nschneid** [comment]
I think so. But I'd want to see more examples to know whether that's always the case.

**Comment by danielhers** [comment]
@omriabnd what's your opinion?

**Comment by omriabnd** [comment]
I don't know. In some cases it could be ambiguous. I don't think they should have marked it as CMR to begin with. How many such cases are there in the corpus?

**Comment by danielhers** [comment]
Just 4 out of 174:
```
$ git grep Coordinated_Main_Rel 845017c8d |wc -l
174
$ git grep -A2 Coordinated_Main_Rel 845017c8d | grep 'tag="A"' | wc -l
4

```

**Comment by danielhers** [comment]
So should I change the handling in normalization.py or leave it this way?

**Comment by omriabnd** [comment]
I would leave it this way, and update the guidelines that cases like this
should not be annotated with CMR.

**Comment by nschneid** [comment]
Can it be flagged as an error in normalization/validation code?
